# ============================================================
# Authors: Brad Heffernan - Erik Dubois - Cameron Percival
# ============================================================

import functools
import ai


def gui(self, Gtk, vboxstack_ai, fn):
    """create a gui"""
    hbox_title = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_title_label = Gtk.Label(xalign=0)
    hbox_title_label.set_text("AI Tools")
    hbox_title_label.set_name("title")
    hbox_title_label.set_margin_start(10)
    hbox_title_label.set_margin_end(10)
    hbox_title.append(hbox_title_label)

    hbox_sep = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator.set_hexpand(True)
    hseparator.set_vexpand(False)
    hbox_sep.append(hseparator)

    # Section 1: Local LLM Runners
    hbox_section1 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section1_label = Gtk.Label(xalign=0)
    hbox_section1_label.set_markup("<b>Local LLM Runners</b>")
    hbox_section1_label.set_margin_start(10)
    hbox_section1_label.set_margin_top(15)
    hbox_section1_label.set_margin_bottom(10)
    hbox_section1.append(hbox_section1_label)

    # Ollama
    hbox_ollama = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_ollama_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    self.lbl_ai_ollama = Gtk.Label(xalign=0)
    self.lbl_ai_ollama.set_markup(
        "Ollama - Local LLM runner" + (" <b>installed</b>" if fn.path.exists("/usr/bin/ollama") else "")
    )
    hbox_ollama_label.append(self.lbl_ai_ollama)
    self.btn_ai_ollama_link = Gtk.Button()
    lbl_ai_ollama_link = Gtk.Label()
    lbl_ai_ollama_link.set_markup("<i>link</i>")
    self.btn_ai_ollama_link.set_child(lbl_ai_ollama_link)
    self.btn_ai_ollama_link.set_css_classes(["flat"])
    self.btn_ai_ollama_link.connect("clicked", functools.partial(ai.on_click_ai_ollama_link, self))
    ai.attach_link_context_menu(self, self.btn_ai_ollama_link, ai.URL_OLLAMA)
    hbox_ollama_label.append(self.btn_ai_ollama_link)
    self.btn_ai_ollama = Gtk.Button(label="Remove" if fn.path.exists("/usr/bin/ollama") else "Install")
    self.btn_ai_ollama.connect("clicked", functools.partial(ai.on_click_ai_ollama, self))
    hbox_ollama_label.set_margin_start(20)
    hbox_ollama_label.set_margin_end(10)
    hbox_ollama_label.set_hexpand(True)
    hbox_ollama.append(hbox_ollama_label)
    self.btn_ai_ollama.set_margin_start(10)
    self.btn_ai_ollama.set_margin_end(10)
    hbox_ollama.append(self.btn_ai_ollama)

    # Open WebUI
    hbox_webui = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_webui_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    self.lbl_ai_webui = Gtk.Label(xalign=0)
    self.lbl_ai_webui.set_markup(
        "Open WebUI - Browser UI for Ollama"
        + (" <b>installed</b>" if fn.path.exists("/usr/bin/open-webui") else "")
    )
    hbox_webui_label.append(self.lbl_ai_webui)
    self.btn_ai_webui_link = Gtk.Button()
    lbl_ai_webui_link = Gtk.Label()
    lbl_ai_webui_link.set_markup("<i>link</i>")
    self.btn_ai_webui_link.set_child(lbl_ai_webui_link)
    self.btn_ai_webui_link.set_css_classes(["flat"])
    self.btn_ai_webui_link.connect("clicked", functools.partial(ai.on_click_ai_webui_link, self))
    ai.attach_link_context_menu(self, self.btn_ai_webui_link, ai.URL_WEBUI)
    hbox_webui_label.append(self.btn_ai_webui_link)
    self.btn_ai_webui = Gtk.Button(label="Remove" if fn.path.exists("/usr/bin/open-webui") else "Install")
    self.btn_ai_webui.connect("clicked", functools.partial(ai.on_click_ai_webui, self))
    hbox_webui_label.set_margin_start(20)
    hbox_webui_label.set_margin_end(10)
    hbox_webui_label.set_hexpand(True)
    hbox_webui.append(hbox_webui_label)
    self.btn_ai_webui.set_margin_start(10)
    self.btn_ai_webui.set_margin_end(10)
    hbox_webui.append(self.btn_ai_webui)

    # Section 2: CLI Coding Assistants
    hbox_section2 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section2_label = Gtk.Label(xalign=0)
    hbox_section2_label.set_markup("<b>CLI Coding Assistants</b>")
    hbox_section2_label.set_margin_start(10)
    hbox_section2_label.set_margin_top(15)
    hbox_section2_label.set_margin_bottom(10)
    hbox_section2.append(hbox_section2_label)

    # Claude Code
    hbox_claude = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_claude_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    self.lbl_ai_claude = Gtk.Label(xalign=0)
    self.lbl_ai_claude.set_markup(
        "Claude Code - Anthropic CLI" + (" <b>installed</b>" if fn.path.exists("/usr/bin/claude") else "")
    )
    hbox_claude_label.append(self.lbl_ai_claude)
    self.btn_ai_claude_link = Gtk.Button()
    lbl_ai_claude_link = Gtk.Label()
    lbl_ai_claude_link.set_markup("<i>link</i>")
    self.btn_ai_claude_link.set_child(lbl_ai_claude_link)
    self.btn_ai_claude_link.set_css_classes(["flat"])
    self.btn_ai_claude_link.connect("clicked", functools.partial(ai.on_click_ai_claude_link, self))
    ai.attach_link_context_menu(self, self.btn_ai_claude_link, ai.URL_CLAUDE_CLI)
    hbox_claude_label.append(self.btn_ai_claude_link)
    self.btn_ai_claude = Gtk.Button(label="Remove" if fn.path.exists("/usr/bin/claude") else "Install")
    self.btn_ai_claude.connect("clicked", functools.partial(ai.on_click_ai_claude, self))
    hbox_claude_label.set_margin_start(20)
    hbox_claude_label.set_margin_end(10)
    hbox_claude_label.set_hexpand(True)
    hbox_claude.append(hbox_claude_label)
    self.btn_ai_claude.set_margin_start(10)
    self.btn_ai_claude.set_margin_end(10)
    hbox_claude.append(self.btn_ai_claude)

    # Aider
    hbox_aider = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_aider_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    self.lbl_ai_aider = Gtk.Label(xalign=0)
    aider_installed = fn.path.exists("/usr/bin/aider") or fn.path.exists(f"/home/{fn.sudo_username}/.local/bin/aider")
    self.lbl_ai_aider.set_markup("Aider - AI pair programming" + (" <b>installed</b>" if aider_installed else ""))
    hbox_aider_label.append(self.lbl_ai_aider)
    self.btn_ai_aider_link = Gtk.Button()
    lbl_ai_aider_link = Gtk.Label()
    lbl_ai_aider_link.set_markup("<i>link</i>")
    self.btn_ai_aider_link.set_child(lbl_ai_aider_link)
    self.btn_ai_aider_link.set_css_classes(["flat"])
    self.btn_ai_aider_link.connect("clicked", functools.partial(ai.on_click_ai_aider_link, self))
    ai.attach_link_context_menu(self, self.btn_ai_aider_link, ai.URL_AIDER)
    hbox_aider_label.append(self.btn_ai_aider_link)
    self.btn_ai_aider = Gtk.Button(label="Remove" if aider_installed else "Install")
    self.btn_ai_aider.connect("clicked", functools.partial(ai.on_click_ai_aider, self))
    hbox_aider_label.set_margin_start(20)
    hbox_aider_label.set_margin_end(10)
    hbox_aider_label.set_hexpand(True)
    hbox_aider.append(hbox_aider_label)
    self.btn_ai_aider.set_margin_start(10)
    self.btn_ai_aider.set_margin_end(10)
    hbox_aider.append(self.btn_ai_aider)

    # OpenAI Codex CLI
    hbox_codex = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_codex_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    self.lbl_ai_codex = Gtk.Label(xalign=0)
    codex_installed = (
        fn.path.exists("/usr/bin/codex")
        or fn.path.exists("/usr/local/bin/codex")
        or fn.path.exists(f"/home/{fn.sudo_username}/.local/bin/codex")
        or fn.path.exists(f"/home/{fn.sudo_username}/.npm-global/bin/codex")
    )
    self.lbl_ai_codex.set_markup("OpenAI Codex CLI" + (" <b>installed</b>" if codex_installed else ""))
    hbox_codex_label.append(self.lbl_ai_codex)
    self.btn_ai_codex_link = Gtk.Button()
    lbl_ai_codex_link = Gtk.Label()
    lbl_ai_codex_link.set_markup("<i>link</i>")
    self.btn_ai_codex_link.set_child(lbl_ai_codex_link)
    self.btn_ai_codex_link.set_css_classes(["flat"])
    self.btn_ai_codex_link.connect("clicked", functools.partial(ai.on_click_ai_codex_link, self))
    ai.attach_link_context_menu(self, self.btn_ai_codex_link, ai.URL_CODEX)
    hbox_codex_label.append(self.btn_ai_codex_link)
    self.btn_ai_codex = Gtk.Button(label="Remove" if codex_installed else "Install")
    self.btn_ai_codex.connect("clicked", functools.partial(ai.on_click_ai_codex, self))
    hbox_codex_label.set_margin_start(20)
    hbox_codex_label.set_margin_end(10)
    hbox_codex_label.set_hexpand(True)
    hbox_codex.append(hbox_codex_label)
    self.btn_ai_codex.set_margin_start(10)
    self.btn_ai_codex.set_margin_end(10)
    hbox_codex.append(self.btn_ai_codex)

    # Google Gemini CLI
    hbox_gemini = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_gemini_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    self.lbl_ai_gemini = Gtk.Label(xalign=0)
    gemini_installed = (
        fn.path.exists("/usr/bin/gemini")
        or fn.path.exists("/usr/local/bin/gemini")
        or fn.path.exists(f"/home/{fn.sudo_username}/.local/bin/gemini")
        or fn.path.exists(f"/home/{fn.sudo_username}/.npm-global/bin/gemini")
    )
    self.lbl_ai_gemini.set_markup("Google Gemini CLI" + (" <b>installed</b>" if gemini_installed else ""))
    hbox_gemini_label.append(self.lbl_ai_gemini)
    self.btn_ai_gemini_link = Gtk.Button()
    lbl_ai_gemini_link = Gtk.Label()
    lbl_ai_gemini_link.set_markup("<i>link</i>")
    self.btn_ai_gemini_link.set_child(lbl_ai_gemini_link)
    self.btn_ai_gemini_link.set_css_classes(["flat"])
    self.btn_ai_gemini_link.connect("clicked", functools.partial(ai.on_click_ai_gemini_link, self))
    ai.attach_link_context_menu(self, self.btn_ai_gemini_link, ai.URL_GEMINI_CLI)
    hbox_gemini_label.append(self.btn_ai_gemini_link)
    self.btn_ai_gemini = Gtk.Button(label="Remove" if gemini_installed else "Install")
    self.btn_ai_gemini.connect("clicked", functools.partial(ai.on_click_ai_gemini, self))
    hbox_gemini_label.set_margin_start(20)
    hbox_gemini_label.set_margin_end(10)
    hbox_gemini_label.set_hexpand(True)
    hbox_gemini.append(hbox_gemini_label)
    self.btn_ai_gemini.set_margin_start(10)
    self.btn_ai_gemini.set_margin_end(10)
    hbox_gemini.append(self.btn_ai_gemini)

    # OpenCode
    hbox_opencode = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_opencode_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    self.lbl_ai_opencode = Gtk.Label(xalign=0)
    opencode_installed = (
        fn.path.exists("/usr/bin/opencode")
        or fn.path.exists("/usr/local/bin/opencode")
        or fn.path.exists(f"/home/{fn.sudo_username}/.local/bin/opencode")
        or fn.path.exists(f"/home/{fn.sudo_username}/.npm-global/bin/opencode")
    )
    self.lbl_ai_opencode.set_markup(
        "OpenCode - TUI AI coding assistant" + (" <b>installed</b>" if opencode_installed else "")
    )
    hbox_opencode_label.append(self.lbl_ai_opencode)
    self.btn_ai_opencode_link = Gtk.Button()
    lbl_ai_opencode_link = Gtk.Label()
    lbl_ai_opencode_link.set_markup("<i>link</i>")
    self.btn_ai_opencode_link.set_child(lbl_ai_opencode_link)
    self.btn_ai_opencode_link.set_css_classes(["flat"])
    self.btn_ai_opencode_link.connect("clicked", functools.partial(ai.on_click_ai_opencode_link, self))
    ai.attach_link_context_menu(self, self.btn_ai_opencode_link, ai.URL_OPENCODE)
    hbox_opencode_label.append(self.btn_ai_opencode_link)
    self.btn_ai_opencode = Gtk.Button(label="Remove" if opencode_installed else "Install")
    self.btn_ai_opencode.connect("clicked", functools.partial(ai.on_click_ai_opencode, self))
    hbox_opencode_label.set_margin_start(20)
    hbox_opencode_label.set_margin_end(10)
    hbox_opencode_label.set_hexpand(True)
    hbox_opencode.append(hbox_opencode_label)
    self.btn_ai_opencode.set_margin_start(10)
    self.btn_ai_opencode.set_margin_end(10)
    hbox_opencode.append(self.btn_ai_opencode)

    # GitHub Copilot CLI
    hbox_copilot = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_copilot_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    self.lbl_ai_copilot = Gtk.Label(xalign=0)
    copilot_installed = (
        fn.path.exists("/usr/bin/copilot")
        or fn.path.exists("/usr/local/bin/copilot")
        or fn.path.exists(f"/home/{fn.sudo_username}/.local/bin/copilot")
        or fn.path.exists(f"/home/{fn.sudo_username}/.npm-global/bin/copilot")
    )
    self.lbl_ai_copilot.set_markup(
        "GitHub Copilot CLI" + (" <b>installed</b>" if copilot_installed else "")
    )
    hbox_copilot_label.append(self.lbl_ai_copilot)
    self.btn_ai_copilot_link = Gtk.Button()
    lbl_ai_copilot_link = Gtk.Label()
    lbl_ai_copilot_link.set_markup("<i>link</i>")
    self.btn_ai_copilot_link.set_child(lbl_ai_copilot_link)
    self.btn_ai_copilot_link.set_css_classes(["flat"])
    self.btn_ai_copilot_link.connect("clicked", functools.partial(ai.on_click_ai_copilot_link, self))
    ai.attach_link_context_menu(self, self.btn_ai_copilot_link, ai.URL_COPILOT)
    hbox_copilot_label.append(self.btn_ai_copilot_link)
    self.btn_ai_copilot = Gtk.Button(label="Remove" if copilot_installed else "Install")
    self.btn_ai_copilot.connect("clicked", functools.partial(ai.on_click_ai_copilot, self))
    hbox_copilot_label.set_margin_start(20)
    hbox_copilot_label.set_margin_end(10)
    hbox_copilot_label.set_hexpand(True)
    hbox_copilot.append(hbox_copilot_label)
    self.btn_ai_copilot.set_margin_start(10)
    self.btn_ai_copilot.set_margin_end(10)
    hbox_copilot.append(self.btn_ai_copilot)

    # Section 3: Web Apps
    hbox_section3 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section3_label = Gtk.Label(xalign=0)
    hbox_section3_label.set_markup("<b>Web Apps</b>")
    hbox_section3_label.set_margin_start(10)
    hbox_section3_label.set_margin_top(15)
    hbox_section3_label.set_margin_bottom(10)
    hbox_section3.append(hbox_section3_label)

    # ChatGPT
    hbox_chatgpt = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_chatgpt_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    lbl_chatgpt = Gtk.Label(xalign=0)
    lbl_chatgpt.set_text("ChatGPT")
    hbox_chatgpt_label.append(lbl_chatgpt)
    btn_chatgpt_link = Gtk.Button()
    lbl_chatgpt_link = Gtk.Label()
    lbl_chatgpt_link.set_markup("<i>link</i>")
    btn_chatgpt_link.set_child(lbl_chatgpt_link)
    btn_chatgpt_link.set_css_classes(["flat"])
    btn_chatgpt_link.connect("clicked", functools.partial(ai.on_click_ai_chatgpt_link, self))
    ai.attach_link_context_menu(self, btn_chatgpt_link, ai.URL_CHATGPT_DOCS)
    hbox_chatgpt_label.append(btn_chatgpt_link)
    btn_chatgpt = Gtk.Button(label="Open")
    btn_chatgpt.connect("clicked", functools.partial(ai.on_click_ai_chatgpt, self))
    hbox_chatgpt_label.set_margin_start(20)
    hbox_chatgpt_label.set_margin_end(10)
    hbox_chatgpt_label.set_hexpand(True)
    hbox_chatgpt.append(hbox_chatgpt_label)
    btn_chatgpt.set_margin_start(10)
    btn_chatgpt.set_margin_end(10)
    hbox_chatgpt.append(btn_chatgpt)

    # Claude.ai
    hbox_claude_web = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_claude_web_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    lbl_claude_web = Gtk.Label(xalign=0)
    lbl_claude_web.set_text("Claude.ai")
    hbox_claude_web_label.append(lbl_claude_web)
    btn_claude_web_link = Gtk.Button()
    lbl_claude_web_link = Gtk.Label()
    lbl_claude_web_link.set_markup("<i>link</i>")
    btn_claude_web_link.set_child(lbl_claude_web_link)
    btn_claude_web_link.set_css_classes(["flat"])
    btn_claude_web_link.connect("clicked", functools.partial(ai.on_click_ai_claude_web_link, self))
    ai.attach_link_context_menu(self, btn_claude_web_link, ai.URL_CLAUDE_WEB_DOCS)
    hbox_claude_web_label.append(btn_claude_web_link)
    btn_claude_web = Gtk.Button(label="Open")
    btn_claude_web.connect("clicked", functools.partial(ai.on_click_ai_claude_web, self))
    hbox_claude_web_label.set_margin_start(20)
    hbox_claude_web_label.set_margin_end(10)
    hbox_claude_web_label.set_hexpand(True)
    hbox_claude_web.append(hbox_claude_web_label)
    btn_claude_web.set_margin_start(10)
    btn_claude_web.set_margin_end(10)
    hbox_claude_web.append(btn_claude_web)

    # Google Gemini
    hbox_gemini_web = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_gemini_web_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    lbl_gemini_web = Gtk.Label(xalign=0)
    lbl_gemini_web.set_text("Google Gemini")
    hbox_gemini_web_label.append(lbl_gemini_web)
    btn_gemini_web_link = Gtk.Button()
    lbl_gemini_web_link = Gtk.Label()
    lbl_gemini_web_link.set_markup("<i>link</i>")
    btn_gemini_web_link.set_child(lbl_gemini_web_link)
    btn_gemini_web_link.set_css_classes(["flat"])
    btn_gemini_web_link.connect("clicked", functools.partial(ai.on_click_ai_gemini_web_link, self))
    ai.attach_link_context_menu(self, btn_gemini_web_link, ai.URL_GEMINI_WEB_DOCS)
    hbox_gemini_web_label.append(btn_gemini_web_link)
    btn_gemini_web = Gtk.Button(label="Open")
    btn_gemini_web.connect("clicked", functools.partial(ai.on_click_ai_gemini_web, self))
    hbox_gemini_web_label.set_margin_start(20)
    hbox_gemini_web_label.set_margin_end(10)
    hbox_gemini_web_label.set_hexpand(True)
    hbox_gemini_web.append(hbox_gemini_web_label)
    btn_gemini_web.set_margin_start(10)
    btn_gemini_web.set_margin_end(10)
    hbox_gemini_web.append(btn_gemini_web)

    # Perplexity
    hbox_perplexity = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_perplexity_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    lbl_perplexity = Gtk.Label(xalign=0)
    lbl_perplexity.set_text("Perplexity")
    hbox_perplexity_label.append(lbl_perplexity)
    btn_perplexity_link = Gtk.Button()
    lbl_perplexity_link = Gtk.Label()
    lbl_perplexity_link.set_markup("<i>link</i>")
    btn_perplexity_link.set_child(lbl_perplexity_link)
    btn_perplexity_link.set_css_classes(["flat"])
    btn_perplexity_link.connect("clicked", functools.partial(ai.on_click_ai_perplexity_link, self))
    ai.attach_link_context_menu(self, btn_perplexity_link, ai.URL_PERPLEXITY_DOCS)
    hbox_perplexity_label.append(btn_perplexity_link)
    btn_perplexity = Gtk.Button(label="Open")
    btn_perplexity.connect("clicked", functools.partial(ai.on_click_ai_perplexity, self))
    hbox_perplexity_label.set_margin_start(20)
    hbox_perplexity_label.set_margin_end(10)
    hbox_perplexity_label.set_hexpand(True)
    hbox_perplexity.append(hbox_perplexity_label)
    btn_perplexity.set_margin_start(10)
    btn_perplexity.set_margin_end(10)
    hbox_perplexity.append(btn_perplexity)

    # Section 4: Image Generation
    hbox_section4 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section4_label = Gtk.Label(xalign=0)
    hbox_section4_label.set_markup("<b>Image Generation</b>")
    hbox_section4_label.set_margin_start(10)
    hbox_section4_label.set_margin_top(15)
    hbox_section4_label.set_margin_bottom(10)
    hbox_section4.append(hbox_section4_label)

    # DALL-E 3
    hbox_dalle = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_dalle_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    lbl_dalle = Gtk.Label(xalign=0)
    lbl_dalle.set_text("DALL-E 3")
    hbox_dalle_label.append(lbl_dalle)
    btn_dalle_link = Gtk.Button()
    lbl_dalle_link = Gtk.Label()
    lbl_dalle_link.set_markup("<i>link</i>")
    btn_dalle_link.set_child(lbl_dalle_link)
    btn_dalle_link.set_css_classes(["flat"])
    btn_dalle_link.connect("clicked", functools.partial(ai.on_click_ai_dalle_link, self))
    ai.attach_link_context_menu(self, btn_dalle_link, ai.URL_DALLE_DOCS)
    hbox_dalle_label.append(btn_dalle_link)
    btn_dalle = Gtk.Button(label="Open")
    btn_dalle.connect("clicked", functools.partial(ai.on_click_ai_dalle, self))
    hbox_dalle_label.set_margin_start(20)
    hbox_dalle_label.set_margin_end(10)
    hbox_dalle_label.set_hexpand(True)
    hbox_dalle.append(hbox_dalle_label)
    btn_dalle.set_margin_start(10)
    btn_dalle.set_margin_end(10)
    hbox_dalle.append(btn_dalle)

    # Midjourney
    hbox_midjourney = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_midjourney_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    lbl_midjourney = Gtk.Label(xalign=0)
    lbl_midjourney.set_text("Midjourney")
    hbox_midjourney_label.append(lbl_midjourney)
    btn_midjourney_link = Gtk.Button()
    lbl_midjourney_link = Gtk.Label()
    lbl_midjourney_link.set_markup("<i>link</i>")
    btn_midjourney_link.set_child(lbl_midjourney_link)
    btn_midjourney_link.set_css_classes(["flat"])
    btn_midjourney_link.connect("clicked", functools.partial(ai.on_click_ai_midjourney_link, self))
    ai.attach_link_context_menu(self, btn_midjourney_link, ai.URL_MIDJOURNEY_DOCS)
    hbox_midjourney_label.append(btn_midjourney_link)
    btn_midjourney = Gtk.Button(label="Open")
    btn_midjourney.connect("clicked", functools.partial(ai.on_click_ai_midjourney, self))
    hbox_midjourney_label.set_margin_start(20)
    hbox_midjourney_label.set_margin_end(10)
    hbox_midjourney_label.set_hexpand(True)
    hbox_midjourney.append(hbox_midjourney_label)
    btn_midjourney.set_margin_start(10)
    btn_midjourney.set_margin_end(10)
    hbox_midjourney.append(btn_midjourney)

    # Leonardo.ai
    hbox_leonardo = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_leonardo_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    lbl_leonardo = Gtk.Label(xalign=0)
    lbl_leonardo.set_text("Leonardo.ai")
    hbox_leonardo_label.append(lbl_leonardo)
    btn_leonardo_link = Gtk.Button()
    lbl_leonardo_link = Gtk.Label()
    lbl_leonardo_link.set_markup("<i>link</i>")
    btn_leonardo_link.set_child(lbl_leonardo_link)
    btn_leonardo_link.set_css_classes(["flat"])
    btn_leonardo_link.connect("clicked", functools.partial(ai.on_click_ai_leonardo_link, self))
    ai.attach_link_context_menu(self, btn_leonardo_link, ai.URL_LEONARDO_DOCS)
    hbox_leonardo_label.append(btn_leonardo_link)
    btn_leonardo = Gtk.Button(label="Open")
    btn_leonardo.connect("clicked", functools.partial(ai.on_click_ai_leonardo, self))
    hbox_leonardo_label.set_margin_start(20)
    hbox_leonardo_label.set_margin_end(10)
    hbox_leonardo_label.set_hexpand(True)
    hbox_leonardo.append(hbox_leonardo_label)
    btn_leonardo.set_margin_start(10)
    btn_leonardo.set_margin_end(10)
    hbox_leonardo.append(btn_leonardo)

    # Adobe Firefly
    hbox_firefly = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_firefly_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
    lbl_firefly = Gtk.Label(xalign=0)
    lbl_firefly.set_text("Adobe Firefly")
    hbox_firefly_label.append(lbl_firefly)
    btn_firefly_link = Gtk.Button()
    lbl_firefly_link = Gtk.Label()
    lbl_firefly_link.set_markup("<i>link</i>")
    btn_firefly_link.set_child(lbl_firefly_link)
    btn_firefly_link.set_css_classes(["flat"])
    btn_firefly_link.connect("clicked", functools.partial(ai.on_click_ai_firefly_link, self))
    ai.attach_link_context_menu(self, btn_firefly_link, ai.URL_FIREFLY_DOCS)
    hbox_firefly_label.append(btn_firefly_link)
    btn_firefly = Gtk.Button(label="Open")
    btn_firefly.connect("clicked", functools.partial(ai.on_click_ai_firefly, self))
    hbox_firefly_label.set_margin_start(20)
    hbox_firefly_label.set_margin_end(10)
    hbox_firefly_label.set_hexpand(True)
    hbox_firefly.append(hbox_firefly_label)
    btn_firefly.set_margin_start(10)
    btn_firefly.set_margin_end(10)
    hbox_firefly.append(btn_firefly)

    # ======================================================================
    #                       VBOX STACK
    # ======================================================================

    vboxstack_ai.append(hbox_title)
    vboxstack_ai.append(hbox_sep)
    vboxstack_ai.append(hbox_section1)
    vboxstack_ai.append(hbox_ollama)
    vboxstack_ai.append(hbox_webui)
    vboxstack_ai.append(hbox_section2)
    vboxstack_ai.append(hbox_claude)
    vboxstack_ai.append(hbox_aider)
    vboxstack_ai.append(hbox_codex)
    vboxstack_ai.append(hbox_gemini)
    vboxstack_ai.append(hbox_opencode)
    vboxstack_ai.append(hbox_copilot)
    vboxstack_ai.append(hbox_section3)
    vboxstack_ai.append(hbox_chatgpt)
    vboxstack_ai.append(hbox_claude_web)
    vboxstack_ai.append(hbox_gemini_web)
    vboxstack_ai.append(hbox_perplexity)
    vboxstack_ai.append(hbox_section4)
    vboxstack_ai.append(hbox_dalle)
    vboxstack_ai.append(hbox_midjourney)
    vboxstack_ai.append(hbox_leonardo)
    vboxstack_ai.append(hbox_firefly)
