# ============================================================
# Authors: Brad Heffernan - Erik Dubois - Cameron Percival
# ============================================================

import functools
import log_callbacks


def gui(self, Gtk, vboxstack_logging, fn):
    """create a gui"""
    hbox_title = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_title_label = Gtk.Label(xalign=0)
    hbox_title_label.set_text("Investigate your logs")
    hbox_title_label.set_name("title")
    hbox_title_label.set_margin_start(10)
    hbox_title_label.set_margin_end(10)
    hbox_title.append(hbox_title_label)

    hbox_sep = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator.set_hexpand(True)
    hseparator.set_vexpand(False)
    hbox_sep.append(hseparator)

    hbox_section_journal = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section_journal_lbl = Gtk.Label(xalign=0)
    hbox_section_journal_lbl.set_markup("<b>Journal</b>")
    hbox_section_journal_lbl.set_margin_start(10)
    hbox_section_journal_lbl.set_margin_top(10)
    hbox_section_journal_lbl.set_margin_bottom(5)
    hbox_section_journal.append(hbox_section_journal_lbl)

    hbox_current_boot = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_current_boot_label = Gtk.Label(xalign=0)
    hbox_current_boot_label.set_text("View current boot journal")
    btn_log_current_boot = Gtk.Button(label="Open")
    btn_log_current_boot.connect("clicked", functools.partial(log_callbacks.on_click_log_current_boot, self))
    hbox_current_boot_label.set_margin_start(10)
    hbox_current_boot_label.set_margin_end(10)
    hbox_current_boot_label.set_hexpand(True)
    hbox_current_boot.append(hbox_current_boot_label)
    btn_log_current_boot.set_margin_start(10)
    btn_log_current_boot.set_margin_end(10)
    hbox_current_boot.append(btn_log_current_boot)

    hbox_prev_boot = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_prev_boot_label = Gtk.Label(xalign=0)
    hbox_prev_boot_label.set_text("View previous boot journal")
    btn_log_prev_boot = Gtk.Button(label="Open")
    btn_log_prev_boot.connect("clicked", functools.partial(log_callbacks.on_click_log_prev_boot, self))
    hbox_prev_boot_label.set_margin_start(10)
    hbox_prev_boot_label.set_margin_end(10)
    hbox_prev_boot_label.set_hexpand(True)
    hbox_prev_boot.append(hbox_prev_boot_label)
    btn_log_prev_boot.set_margin_start(10)
    btn_log_prev_boot.set_margin_end(10)
    hbox_prev_boot.append(btn_log_prev_boot)

    hbox_journal_errors = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_journal_errors_label = Gtk.Label(xalign=0)
    hbox_journal_errors_label.set_text("View journal errors (current boot)")
    btn_log_errors = Gtk.Button(label="Open")
    btn_log_errors.connect("clicked", functools.partial(log_callbacks.on_click_log_errors, self))
    hbox_journal_errors_label.set_margin_start(10)
    hbox_journal_errors_label.set_margin_end(10)
    hbox_journal_errors_label.set_hexpand(True)
    hbox_journal_errors.append(hbox_journal_errors_label)
    btn_log_errors.set_margin_start(10)
    btn_log_errors.set_margin_end(10)
    hbox_journal_errors.append(btn_log_errors)

    hbox_recent_journal = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_recent_journal_label = Gtk.Label(xalign=0)
    hbox_recent_journal_label.set_text("View recent journal (last 20 minutes)")
    btn_log_recent = Gtk.Button(label="Open")
    btn_log_recent.connect("clicked", functools.partial(log_callbacks.on_click_log_recent, self))
    hbox_recent_journal_label.set_margin_start(10)
    hbox_recent_journal_label.set_margin_end(10)
    hbox_recent_journal_label.set_hexpand(True)
    hbox_recent_journal.append(hbox_recent_journal_label)
    btn_log_recent.set_margin_start(10)
    btn_log_recent.set_margin_end(10)
    hbox_recent_journal.append(btn_log_recent)

    hbox_section_system_logs = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section_system_logs_lbl = Gtk.Label(xalign=0)
    hbox_section_system_logs_lbl.set_markup("<b>System Logs</b>")
    hbox_section_system_logs_lbl.set_margin_start(10)
    hbox_section_system_logs_lbl.set_margin_top(10)
    hbox_section_system_logs_lbl.set_margin_bottom(5)
    hbox_section_system_logs.append(hbox_section_system_logs_lbl)

    hbox_xorg_log = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_xorg_log_label = Gtk.Label(xalign=0)
    hbox_xorg_log_label.set_text("View Xorg log")
    btn_log_xorg = Gtk.Button(label="Open")
    btn_log_xorg.connect("clicked", functools.partial(log_callbacks.on_click_log_xorg, self))
    hbox_xorg_log_label.set_margin_start(10)
    hbox_xorg_log_label.set_margin_end(10)
    hbox_xorg_log_label.set_hexpand(True)
    hbox_xorg_log.append(hbox_xorg_log_label)
    btn_log_xorg.set_margin_start(10)
    btn_log_xorg.set_margin_end(10)
    hbox_xorg_log.append(btn_log_xorg)

    if fn.is_wayland_session():
        hbox_wayland_log = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        hbox_wayland_log_label = Gtk.Label(xalign=0)
        hbox_wayland_log_label.set_text("View Wayland compositor log")
        btn_log_wayland = Gtk.Button(label="Open")
        btn_log_wayland.connect("clicked", functools.partial(log_callbacks.on_click_log_wayland, self))
        hbox_wayland_log_label.set_margin_start(10)
        hbox_wayland_log_label.set_margin_end(10)
        hbox_wayland_log_label.set_hexpand(True)
        hbox_wayland_log.append(hbox_wayland_log_label)
        btn_log_wayland.set_margin_start(10)
        btn_log_wayland.set_margin_end(10)
        hbox_wayland_log.append(btn_log_wayland)

    hbox_pacman_log = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_pacman_log_label = Gtk.Label(xalign=0)
    hbox_pacman_log_label.set_text("View pacman log")
    btn_log_pacman = Gtk.Button(label="Open")
    btn_log_pacman.connect("clicked", functools.partial(log_callbacks.on_click_log_pacman, self))
    hbox_pacman_log_label.set_margin_start(10)
    hbox_pacman_log_label.set_margin_end(10)
    hbox_pacman_log_label.set_hexpand(True)
    hbox_pacman_log.append(hbox_pacman_log_label)
    btn_log_pacman.set_margin_start(10)
    btn_log_pacman.set_margin_end(10)
    hbox_pacman_log.append(btn_log_pacman)

    hbox_xsession_errors = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_xsession_errors_label = Gtk.Label(xalign=0)
    hbox_xsession_errors_label.set_text("View X session errors (~/.xsession-errors or Xorg.0.log)")
    btn_log_xsession = Gtk.Button(label="Open")
    btn_log_xsession.connect("clicked", functools.partial(log_callbacks.on_click_log_xsession, self))
    hbox_xsession_errors_label.set_margin_start(10)
    hbox_xsession_errors_label.set_margin_end(10)
    hbox_xsession_errors_label.set_hexpand(True)
    hbox_xsession_errors.append(hbox_xsession_errors_label)
    btn_log_xsession.set_margin_start(10)
    btn_log_xsession.set_margin_end(10)
    hbox_xsession_errors.append(btn_log_xsession)

    hbox_section_boot_kernel = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section_boot_kernel_lbl = Gtk.Label(xalign=0)
    hbox_section_boot_kernel_lbl.set_markup("<b>Boot &amp; Kernel</b>")
    hbox_section_boot_kernel_lbl.set_margin_start(10)
    hbox_section_boot_kernel_lbl.set_margin_top(10)
    hbox_section_boot_kernel_lbl.set_margin_bottom(5)
    hbox_section_boot_kernel.append(hbox_section_boot_kernel_lbl)

    hbox_boot_performance = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_boot_performance_label = Gtk.Label(xalign=0)
    hbox_boot_performance_label.set_text("Analyze boot performance (systemd-analyze blame)")
    btn_log_blame = Gtk.Button(label="Open")
    btn_log_blame.connect("clicked", functools.partial(log_callbacks.on_click_log_blame, self))
    hbox_boot_performance_label.set_margin_start(10)
    hbox_boot_performance_label.set_margin_end(10)
    hbox_boot_performance_label.set_hexpand(True)
    hbox_boot_performance.append(hbox_boot_performance_label)
    btn_log_blame.set_margin_start(10)
    btn_log_blame.set_margin_end(10)
    hbox_boot_performance.append(btn_log_blame)

    hbox_dmesg = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_dmesg_label = Gtk.Label(xalign=0)
    hbox_dmesg_label.set_text("View kernel ring buffer (dmesg)")
    btn_log_dmesg = Gtk.Button(label="Open")
    btn_log_dmesg.connect("clicked", functools.partial(log_callbacks.on_click_log_dmesg, self))
    hbox_dmesg_label.set_margin_start(10)
    hbox_dmesg_label.set_margin_end(10)
    hbox_dmesg_label.set_hexpand(True)
    hbox_dmesg.append(hbox_dmesg_label)
    btn_log_dmesg.set_margin_start(10)
    btn_log_dmesg.set_margin_end(10)
    hbox_dmesg.append(btn_log_dmesg)

    # ======================================================================
    #                       VBOX STACK
    # ======================================================================

    vboxstack_logging.append(hbox_title)
    vboxstack_logging.append(hbox_sep)
    vboxstack_logging.append(hbox_section_journal)
    vboxstack_logging.append(hbox_current_boot)
    vboxstack_logging.append(hbox_prev_boot)
    vboxstack_logging.append(hbox_journal_errors)
    vboxstack_logging.append(hbox_recent_journal)
    vboxstack_logging.append(hbox_section_system_logs)
    vboxstack_logging.append(hbox_xorg_log)
    if fn.is_wayland_session():
        vboxstack_logging.append(hbox_wayland_log)
    vboxstack_logging.append(hbox_pacman_log)
    vboxstack_logging.append(hbox_xsession_errors)
    vboxstack_logging.append(hbox_section_boot_kernel)
    vboxstack_logging.append(hbox_boot_performance)
    vboxstack_logging.append(hbox_dmesg)
