# ============================================================
# Authors: Brad Heffernan - Erik Dubois - Cameron Percival
# ============================================================


def gui(self, Gtk, vboxstack27, performance, fn):
    """create the performance gui"""
    hbox1 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox1_label = Gtk.Label(xalign=0)
    hbox1_label.set_text("Performance")
    hbox1_label.set_name("title")
    hbox1_label.set_margin_start(10)
    hbox1_label.set_margin_end(10)
    hbox1.append(hbox1_label)

    hbox0 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator.set_hexpand(True)
    hseparator.set_vexpand(False)
    hbox0.append(hseparator)

    # ============================================================
    # Tuned Block
    # ============================================================

    hbox6b = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator_tuned = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator_tuned.set_hexpand(True)
    hbox6b.append(hseparator_tuned)

    hbox_tuned_title = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_tuned_title_label = Gtk.Label(xalign=0)
    hbox_tuned_title_label.set_text("Tuned")
    hbox_tuned_title_label.set_name("title")
    hbox_tuned_title_label.set_margin_start(10)
    hbox_tuned_title_label.set_margin_end(10)
    hbox_tuned_title.append(hbox_tuned_title_label)

    hbox7 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox7_label = Gtk.Label(xalign=0)
    if fn.check_package_installed("tuned"):
        hbox7_label.set_markup("tuned is <b>installed</b>")
    else:
        hbox7_label.set_text("Install tuned for dynamic system tuning")
    btn_install_tuned = Gtk.Button(label="Install tuned/tuned-ppd")
    btn_install_tuned.connect("clicked", performance.install_tuned_tools, self)
    btn_remove_tuned = Gtk.Button(label="Remove tuned/tuned-ppd")
    btn_remove_tuned.connect("clicked", performance.remove_tuned_tools, self)
    hbox7_label.set_margin_start(10)
    hbox7_label.set_margin_end(10)
    hbox7_label.set_hexpand(True)
    hbox7.append(hbox7_label)
    btn_install_tuned.set_margin_start(10)
    btn_install_tuned.set_margin_end(10)
    hbox7.append(btn_install_tuned)
    btn_remove_tuned.set_margin_start(10)
    btn_remove_tuned.set_margin_end(10)
    hbox7.append(btn_remove_tuned)

    hbox7b = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox7b_label = Gtk.Label(xalign=0)
    hbox7b_label.set_markup(
        "<b>Tuned</b> - Dynamic system tuning for power management\n"
        "<b>Tuned-PPD</b> - Power Profiles Daemon integration for desktop environments\n"
        "If <b>TLP</b> is installed, it will be disabled when Tuned is enabled (they conflict)."
    )
    hbox7b_label.set_margin_start(10)
    hbox7b_label.set_margin_end(10)
    hbox7b.append(hbox7b_label)

    hbox7c = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.enable_tuned = Gtk.Button(label="Enable tuned")
    self.enable_tuned.connect("clicked", performance.enable_tuned_service, self)
    self.disable_tuned = Gtk.Button(label="Disable tuned")
    self.disable_tuned.connect("clicked", performance.disable_tuned_service, self)
    self.restart_tuned = Gtk.Button(label="Restart tuned")
    self.restart_tuned.connect("clicked", performance.restart_tuned_service, self)
    self.enable_tuned.set_margin_start(10)
    self.enable_tuned.set_margin_end(10)
    hbox7c.append(self.enable_tuned)
    self.disable_tuned.set_margin_start(10)
    self.disable_tuned.set_margin_end(10)
    hbox7c.append(self.disable_tuned)
    self.restart_tuned.set_margin_start(10)
    self.restart_tuned.set_margin_end(10)
    hbox7c.append(self.restart_tuned)

    hbox7d = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.enable_tuned_ppd = Gtk.Button(label="Enable tuned-ppd")
    self.enable_tuned_ppd.connect("clicked", performance.enable_tuned_ppd_service, self)
    self.disable_tuned_ppd = Gtk.Button(label="Disable tuned-ppd")
    self.disable_tuned_ppd.connect("clicked", performance.disable_tuned_ppd_service, self)
    self.restart_tuned_ppd = Gtk.Button(label="Restart tuned-ppd")
    self.restart_tuned_ppd.connect("clicked", performance.restart_tuned_ppd_service, self)
    self.enable_tuned_ppd.set_margin_start(10)
    self.enable_tuned_ppd.set_margin_end(10)
    hbox7d.append(self.enable_tuned_ppd)
    self.disable_tuned_ppd.set_margin_start(10)
    self.disable_tuned_ppd.set_margin_end(10)
    hbox7d.append(self.disable_tuned_ppd)
    self.restart_tuned_ppd.set_margin_start(10)
    self.restart_tuned_ppd.set_margin_end(10)
    hbox7d.append(self.restart_tuned_ppd)

    # Tuned Profiles Selection
    hbox7e = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.tuned_profile_status_label = Gtk.Label(xalign=0)
    self.tuned_profile_status_label.set_markup(performance.get_tuned_profile_status_markup())
    self.tuned_profile_status_label.set_margin_start(10)
    self.tuned_profile_status_label.set_margin_end(10)
    self.tuned_profile_status_label.set_hexpand(True)
    hbox7e.append(self.tuned_profile_status_label)

    hbox7f = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    tuned_profile_choices = performance.get_available_tuned_profiles()
    self.tuned_profile_choices = Gtk.DropDown.new_from_strings(tuned_profile_choices)
    active_profile = performance.get_active_tuned_profile()
    if active_profile and active_profile in tuned_profile_choices:
        self.tuned_profile_choices.set_selected(tuned_profile_choices.index(active_profile))
    self.btn_apply_tuned_profile = Gtk.Button(label="Apply Profile")
    self.btn_apply_tuned_profile.connect("clicked", performance.apply_tuned_profile, self)
    hbox7f_label = Gtk.Label(xalign=0)
    hbox7f_label.set_text("Select profile:")
    hbox7f_label.set_margin_start(10)
    hbox7f_label.set_margin_end(10)
    hbox7f.append(hbox7f_label)
    self.tuned_profile_choices.set_margin_start(10)
    self.tuned_profile_choices.set_margin_end(10)
    hbox7f.append(self.tuned_profile_choices)
    self.btn_apply_tuned_profile.set_margin_start(10)
    self.btn_apply_tuned_profile.set_margin_end(10)
    hbox7f.append(self.btn_apply_tuned_profile)

    # Set initial sensitivity for all tuned controls based on installation status
    # Check just "tuned" package, not the combined "tuned tuned-ppd" string
    if not fn.check_package_installed("tuned"):
        self.enable_tuned.set_sensitive(False)
        self.disable_tuned.set_sensitive(False)
        self.restart_tuned.set_sensitive(False)
        self.enable_tuned_ppd.set_sensitive(False)
        self.disable_tuned_ppd.set_sensitive(False)
        self.restart_tuned_ppd.set_sensitive(False)
        self.tuned_profile_choices.set_sensitive(False)
        self.btn_apply_tuned_profile.set_sensitive(False)

    hbox9 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.performance_status_label = Gtk.Label(xalign=0)
    self.performance_status_label.set_markup(
        performance.get_performance_status_markup()
    )
    self.performance_status_label.set_margin_start(10)
    self.performance_status_label.set_margin_end(10)
    hbox9.append(self.performance_status_label)

    hbox10 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator_zram = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator_zram.set_hexpand(True)
    hbox10.append(hseparator_zram)

    hbox11 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox11_label = Gtk.Label(xalign=0)
    hbox11_label.set_text("Swap Management")
    hbox11_label.set_name("title")
    hbox11_label.set_margin_start(10)
    hbox11_label.set_margin_end(10)
    hbox11.append(hbox11_label)

    hbox12 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox12_label = Gtk.Label(xalign=0)
    hbox12_label.set_text("Create or manage a swapfile at /swapfile")
    hbox12_label.set_margin_start(10)
    hbox12_label.set_margin_end(10)
    hbox12_label.set_hexpand(True)
    self.swapfile_size = Gtk.DropDown.new_from_strings(
        ["1G", "2G", "4G", "8G", "16G", "32G"]
    )
    self.swapfile_size.set_selected(1)
    btn_create_swapfile = Gtk.Button(label="Create")
    btn_create_swapfile.connect("clicked", performance.create_swapfile, self)
    btn_remove_swapfile = Gtk.Button(label="Remove")
    btn_remove_swapfile.connect("clicked", performance.remove_swapfile, self)
    hbox12.append(hbox12_label)
    self.swapfile_size.set_margin_start(10)
    self.swapfile_size.set_margin_end(10)
    hbox12.append(self.swapfile_size)
    btn_create_swapfile.set_margin_start(10)
    btn_create_swapfile.set_margin_end(10)
    hbox12.append(btn_create_swapfile)
    btn_remove_swapfile.set_margin_start(10)
    btn_remove_swapfile.set_margin_end(10)
    hbox12.append(btn_remove_swapfile)

    hbox13 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.zram_status_label = Gtk.Label(xalign=0)
    self.zram_status_label.set_markup(performance.get_zram_status_markup())
    self.zram_status_label.set_margin_start(10)
    self.zram_status_label.set_margin_end(10)
    self.zram_status_label.set_hexpand(True)
    self.zram_size = Gtk.DropDown.new_from_strings(
        ["ram / 4", "ram / 2", "ram * 3 / 4", "ram", "1024", "2048", "4096"]
    )
    self.zram_size.set_selected(1)
    btn_enable_zram = Gtk.Button(label="Enable")
    btn_enable_zram.connect("clicked", performance.enable_zram, self)
    btn_disable_zram = Gtk.Button(label="Disable")
    btn_disable_zram.connect("clicked", performance.disable_zram, self)
    hbox13.append(self.zram_status_label)
    self.zram_size.set_margin_start(10)
    self.zram_size.set_margin_end(10)
    hbox13.append(self.zram_size)
    btn_enable_zram.set_margin_start(10)
    btn_enable_zram.set_margin_end(10)
    hbox13.append(btn_enable_zram)
    btn_disable_zram.set_margin_start(10)
    btn_disable_zram.set_margin_end(10)
    hbox13.append(btn_disable_zram)

    hbox14 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator_fstrim = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator_fstrim.set_hexpand(True)
    hbox14.append(hseparator_fstrim)

    hbox15 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox15_label = Gtk.Label(xalign=0)
    hbox15_label.set_text("SSD/NVMe TRIM")
    hbox15_label.set_name("title")
    hbox15_label.set_margin_start(10)
    hbox15_label.set_margin_end(10)
    hbox15.append(hbox15_label)

    hbox16 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.fstrim_status_label = Gtk.Label(xalign=0)
    self.fstrim_status_label.set_markup(performance.get_fstrim_status_markup())
    self.fstrim_status_label.set_margin_start(10)
    self.fstrim_status_label.set_margin_end(10)
    self.fstrim_status_label.set_hexpand(True)
    btn_enable_fstrim = Gtk.Button(label="Enable fstrim.timer")
    btn_enable_fstrim.connect("clicked", performance.enable_fstrim_timer, self)
    btn_disable_fstrim = Gtk.Button(label="Disable")
    btn_disable_fstrim.connect("clicked", performance.disable_fstrim_timer, self)
    btn_run_fstrim = Gtk.Button(label="Run now")
    btn_run_fstrim.connect("clicked", performance.run_fstrim_now, self)
    hbox16.append(self.fstrim_status_label)
    btn_enable_fstrim.set_margin_start(10)
    btn_enable_fstrim.set_margin_end(10)
    hbox16.append(btn_enable_fstrim)
    btn_disable_fstrim.set_margin_start(10)
    btn_disable_fstrim.set_margin_end(10)
    hbox16.append(btn_disable_fstrim)
    btn_run_fstrim.set_margin_start(10)
    btn_run_fstrim.set_margin_end(10)
    hbox16.append(btn_run_fstrim)

    hbox17 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator_irqbalance = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator_irqbalance.set_hexpand(True)
    hbox17.append(hseparator_irqbalance)

    hbox18 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox18_label = Gtk.Label(xalign=0)
    hbox18_label.set_text("IRQ Balancing")
    hbox18_label.set_name("title")
    hbox18_label.set_margin_start(10)
    hbox18_label.set_margin_end(10)
    hbox18.append(hbox18_label)

    hbox19 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.irqbalance_package_label = Gtk.Label(xalign=0)
    if fn.check_package_installed("irqbalance"):
        self.irqbalance_package_label.set_markup(
            "irqbalance package is <b>installed</b>"
        )
    else:
        self.irqbalance_package_label.set_text("Install irqbalance")
    btn_install_irqbalance = Gtk.Button(label="Install irqbalance")
    btn_install_irqbalance.connect("clicked", performance.install_irqbalance, self)
    btn_remove_irqbalance = Gtk.Button(label="Remove irqbalance")
    btn_remove_irqbalance.connect("clicked", performance.remove_irqbalance, self)
    self.irqbalance_package_label.set_margin_start(10)
    self.irqbalance_package_label.set_margin_end(10)
    self.irqbalance_package_label.set_hexpand(True)
    hbox19.append(self.irqbalance_package_label)
    btn_install_irqbalance.set_margin_start(10)
    btn_install_irqbalance.set_margin_end(10)
    hbox19.append(btn_install_irqbalance)
    btn_remove_irqbalance.set_margin_start(10)
    btn_remove_irqbalance.set_margin_end(10)
    hbox19.append(btn_remove_irqbalance)

    hbox20 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.irqbalance_status_label = Gtk.Label(xalign=0)
    self.irqbalance_status_label.set_markup(
        performance.get_irqbalance_status_markup()
    )
    self.irqbalance_status_label.set_margin_start(10)
    self.irqbalance_status_label.set_margin_end(10)
    self.irqbalance_status_label.set_hexpand(True)
    self.enable_irqbalance = Gtk.Button(label="Enable irqbalance")
    self.enable_irqbalance.connect(
        "clicked", performance.enable_irqbalance_service, self
    )
    self.disable_irqbalance = Gtk.Button(label="Disable irqbalance")
    self.disable_irqbalance.connect(
        "clicked", performance.disable_irqbalance_service, self
    )
    hbox20.append(self.irqbalance_status_label)
    self.enable_irqbalance.set_margin_start(10)
    self.enable_irqbalance.set_margin_end(10)
    hbox20.append(self.enable_irqbalance)
    self.disable_irqbalance.set_margin_start(10)
    self.disable_irqbalance.set_margin_end(10)
    hbox20.append(self.disable_irqbalance)

    if not fn.check_package_installed("irqbalance"):
        self.enable_irqbalance.set_sensitive(False)
        self.disable_irqbalance.set_sensitive(False)

    hbox21 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator_ananicy = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator_ananicy.set_hexpand(True)
    hbox21.append(hseparator_ananicy)

    hbox22 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox22_label = Gtk.Label(xalign=0)
    hbox22_label.set_text("Ananicy")
    hbox22_label.set_name("title")
    hbox22_label.set_margin_start(10)
    hbox22_label.set_margin_end(10)
    hbox22.append(hbox22_label)

    hbox23 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.ananicy_package_label = Gtk.Label(xalign=0)
    if fn.check_package_installed("ananicy-cpp") and fn.check_package_installed("cachyos-ananicy-rules-git"):
        self.ananicy_package_label.set_markup(
            "ananicy-cpp and cachyos-ananicy-rules-git are <b>installed</b>"
        )
    elif fn.check_package_installed("ananicy-cpp"):
        self.ananicy_package_label.set_markup(
            "ananicy-cpp is <b>installed</b> (cachyos-ananicy-rules-git not installed)"
        )
    else:
        self.ananicy_package_label.set_text("Install ananicy-cpp and cachyos-ananicy-rules-git")
    btn_install_ananicy = Gtk.Button(label="Install")
    btn_install_ananicy.connect("clicked", performance.install_ananicy, self)
    btn_remove_ananicy = Gtk.Button(label="Remove")
    btn_remove_ananicy.connect("clicked", performance.remove_ananicy, self)
    self.ananicy_package_label.set_margin_start(10)
    self.ananicy_package_label.set_margin_end(10)
    self.ananicy_package_label.set_hexpand(True)
    hbox23.append(self.ananicy_package_label)
    btn_install_ananicy.set_margin_start(10)
    btn_install_ananicy.set_margin_end(10)
    hbox23.append(btn_install_ananicy)
    btn_remove_ananicy.set_margin_start(10)
    btn_remove_ananicy.set_margin_end(10)
    hbox23.append(btn_remove_ananicy)

    hbox24 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.ananicy_status_label = Gtk.Label(xalign=0)
    self.ananicy_status_label.set_markup(performance.get_ananicy_status_markup())
    self.ananicy_status_label.set_margin_start(10)
    self.ananicy_status_label.set_margin_end(10)
    self.ananicy_status_label.set_hexpand(True)
    self.enable_ananicy = Gtk.Button(label="Enable ananicy-cpp")
    self.enable_ananicy.connect("clicked", performance.enable_ananicy_service, self)
    self.disable_ananicy = Gtk.Button(label="Disable ananicy-cpp")
    self.disable_ananicy.connect("clicked", performance.disable_ananicy_service, self)
    hbox24.append(self.ananicy_status_label)
    self.enable_ananicy.set_margin_start(10)
    self.enable_ananicy.set_margin_end(10)
    hbox24.append(self.enable_ananicy)
    self.disable_ananicy.set_margin_start(10)
    self.disable_ananicy.set_margin_end(10)
    hbox24.append(self.disable_ananicy)

    if not fn.check_package_installed("ananicy-cpp"):
        self.enable_ananicy.set_sensitive(False)
        self.disable_ananicy.set_sensitive(False)

    vboxstack27.append(hbox1)
    vboxstack27.append(hbox0)
    vboxstack27.append(hbox6b)
    vboxstack27.append(hbox_tuned_title)
    vboxstack27.append(hbox7)
    vboxstack27.append(hbox7b)
    vboxstack27.append(hbox7c)
    vboxstack27.append(hbox7d)
    vboxstack27.append(hbox7e)
    vboxstack27.append(hbox7f)
    vboxstack27.append(hbox9)
    vboxstack27.append(hbox10)
    vboxstack27.append(hbox11)
    vboxstack27.append(hbox12)
    vboxstack27.append(hbox13)
    vboxstack27.append(hbox14)
    vboxstack27.append(hbox15)
    vboxstack27.append(hbox16)
    vboxstack27.append(hbox17)
    vboxstack27.append(hbox18)
    vboxstack27.append(hbox19)
    vboxstack27.append(hbox20)
    vboxstack27.append(hbox21)
    vboxstack27.append(hbox22)
    vboxstack27.append(hbox23)
    vboxstack27.append(hbox24)
