# ============================================================
# Authors: Brad Heffernan - Erik Dubois - Cameron Percival
# ============================================================

import functools
import system


def gui(self, Gtk, vboxstack_system, fn):
    """create a gui"""
    hbox_title = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_title_label = Gtk.Label(xalign=0)
    hbox_title_label.set_markup("<b>Inspect your hardware and software</b>")
    hbox_title_label.set_name("title")
    hbox_title_label.set_margin_start(10)
    hbox_title_label.set_margin_end(10)
    hbox_title.append(hbox_title_label)

    hbox_sep = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator.set_hexpand(True)
    hseparator.set_vexpand(False)
    hbox_sep.append(hseparator)

    # CPU Info
    hbox_cpu = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_cpu = Gtk.Label(xalign=0)
    lbl_cpu.set_text("CPU Information")
    btn_cpu = Gtk.Button(label="View")
    btn_cpu.connect("clicked", functools.partial(system.on_click_system_cpu, self))
    lbl_cpu.set_margin_start(10)
    lbl_cpu.set_margin_end(10)
    lbl_cpu.set_hexpand(True)
    hbox_cpu.append(lbl_cpu)
    btn_cpu.set_margin_start(10)
    btn_cpu.set_margin_end(10)
    hbox_cpu.append(btn_cpu)

    # Memory & Disk Usage
    hbox_memory_disk = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_memory_disk = Gtk.Label(xalign=0)
    lbl_memory_disk.set_text("Memory and Disk Usage")
    btn_memory_disk = Gtk.Button(label="View")
    btn_memory_disk.connect("clicked", functools.partial(system.on_click_system_memory_disk, self))
    lbl_memory_disk.set_margin_start(10)
    lbl_memory_disk.set_margin_end(10)
    lbl_memory_disk.set_hexpand(True)
    hbox_memory_disk.append(lbl_memory_disk)
    btn_memory_disk.set_margin_start(10)
    btn_memory_disk.set_margin_end(10)
    hbox_memory_disk.append(btn_memory_disk)

    # Block Devices
    hbox_lsblk = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_lsblk = Gtk.Label(xalign=0)
    lbl_lsblk.set_text("Block Devices (lsblk)")
    btn_lsblk = Gtk.Button(label="View")
    btn_lsblk.connect("clicked", functools.partial(system.on_click_system_lsblk, self))
    lbl_lsblk.set_margin_start(10)
    lbl_lsblk.set_margin_end(10)
    lbl_lsblk.set_hexpand(True)
    hbox_lsblk.append(lbl_lsblk)
    btn_lsblk.set_margin_start(10)
    btn_lsblk.set_margin_end(10)
    hbox_lsblk.append(btn_lsblk)

    # PCI Devices
    hbox_lspci = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_lspci = Gtk.Label(xalign=0)
    lbl_lspci.set_text("PCI Devices (lspci)")
    btn_lspci = Gtk.Button(label="View")
    btn_lspci.connect("clicked", functools.partial(system.on_click_system_lspci, self))
    lbl_lspci.set_margin_start(10)
    lbl_lspci.set_margin_end(10)
    lbl_lspci.set_hexpand(True)
    hbox_lspci.append(lbl_lspci)
    btn_lspci.set_margin_start(10)
    btn_lspci.set_margin_end(10)
    hbox_lspci.append(btn_lspci)

    # USB Devices
    hbox_lsusb = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_lsusb = Gtk.Label(xalign=0)
    lbl_lsusb.set_text("USB Devices (lsusb)")
    btn_lsusb = Gtk.Button(label="View")
    btn_lsusb.connect("clicked", functools.partial(system.on_click_system_lsusb, self))
    lbl_lsusb.set_margin_start(10)
    lbl_lsusb.set_margin_end(10)
    lbl_lsusb.set_hexpand(True)
    hbox_lsusb.append(lbl_lsusb)
    btn_lsusb.set_margin_start(10)
    btn_lsusb.set_margin_end(10)
    hbox_lsusb.append(btn_lsusb)

    # Loaded Kernel Modules
    hbox_lsmod = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_lsmod = Gtk.Label(xalign=0)
    lbl_lsmod.set_text("Loaded Kernel Modules (lsmod)")
    btn_lsmod = Gtk.Button(label="View")
    btn_lsmod.connect("clicked", functools.partial(system.on_click_system_lsmod, self))
    lbl_lsmod.set_margin_start(10)
    lbl_lsmod.set_margin_end(10)
    lbl_lsmod.set_hexpand(True)
    hbox_lsmod.append(lbl_lsmod)
    btn_lsmod.set_margin_start(10)
    btn_lsmod.set_margin_end(10)
    hbox_lsmod.append(btn_lsmod)

    # Comprehensive Hardware Info
    hbox_inxi = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_inxi = Gtk.Label(xalign=0)
    lbl_inxi.set_text("Comprehensive Hardware Info (inxi)")
    btn_inxi = Gtk.Button(label="View")
    btn_inxi.connect("clicked", functools.partial(system.on_click_system_inxi, self))
    lbl_inxi.set_margin_start(10)
    lbl_inxi.set_margin_end(10)
    lbl_inxi.set_hexpand(True)
    hbox_inxi.append(lbl_inxi)
    btn_inxi.set_margin_start(10)
    btn_inxi.set_margin_end(10)
    hbox_inxi.append(btn_inxi)

    # Hardware Summary
    hbox_hwinfo = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_hwinfo = Gtk.Label(xalign=0)
    lbl_hwinfo.set_text("Hardware Summary (hwinfo)")
    btn_hwinfo = Gtk.Button(label="View")
    btn_hwinfo.connect("clicked", functools.partial(system.on_click_system_hwinfo, self))
    lbl_hwinfo.set_margin_start(10)
    lbl_hwinfo.set_margin_end(10)
    lbl_hwinfo.set_hexpand(True)
    hbox_hwinfo.append(lbl_hwinfo)
    btn_hwinfo.set_margin_start(10)
    btn_hwinfo.set_margin_end(10)
    hbox_hwinfo.append(btn_hwinfo)

    # Disk Partitions
    hbox_fdisk = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_fdisk = Gtk.Label(xalign=0)
    lbl_fdisk.set_text("Disk Partitions (fdisk -l)")
    btn_fdisk = Gtk.Button(label="View")
    btn_fdisk.connect("clicked", functools.partial(system.on_click_system_fdisk, self))
    lbl_fdisk.set_margin_start(10)
    lbl_fdisk.set_margin_end(10)
    lbl_fdisk.set_hexpand(True)
    hbox_fdisk.append(lbl_fdisk)
    btn_fdisk.set_margin_start(10)
    btn_fdisk.set_margin_end(10)
    hbox_fdisk.append(btn_fdisk)

    # Filesystem Config
    hbox_fstab = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_fstab = Gtk.Label(xalign=0)
    lbl_fstab.set_text("Filesystem Configuration (fstab)")
    btn_fstab = Gtk.Button(label="View")
    btn_fstab.connect("clicked", functools.partial(system.on_click_system_fstab, self))
    lbl_fstab.set_margin_start(10)
    lbl_fstab.set_margin_end(10)
    lbl_fstab.set_hexpand(True)
    hbox_fstab.append(lbl_fstab)
    btn_fstab.set_margin_start(10)
    btn_fstab.set_margin_end(10)
    hbox_fstab.append(btn_fstab)

    # System Overview
    hbox_hostnamectl = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_hostnamectl = Gtk.Label(xalign=0)
    lbl_hostnamectl.set_text("System Overview (hostnamectl)")
    btn_hostnamectl = Gtk.Button(label="View")
    btn_hostnamectl.connect("clicked", functools.partial(system.on_click_system_hostnamectl, self))
    lbl_hostnamectl.set_margin_start(10)
    lbl_hostnamectl.set_margin_end(10)
    lbl_hostnamectl.set_hexpand(True)
    hbox_hostnamectl.append(lbl_hostnamectl)
    btn_hostnamectl.set_margin_start(10)
    btn_hostnamectl.set_margin_end(10)
    hbox_hostnamectl.append(btn_hostnamectl)

    # Locale & Timezone
    hbox_localectl = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_localectl = Gtk.Label(xalign=0)
    lbl_localectl.set_text("Locale and Timezone (localectl)")
    btn_localectl = Gtk.Button(label="View")
    btn_localectl.connect("clicked", functools.partial(system.on_click_system_localectl, self))
    lbl_localectl.set_margin_start(10)
    lbl_localectl.set_margin_end(10)
    lbl_localectl.set_hexpand(True)
    hbox_localectl.append(lbl_localectl)
    btn_localectl.set_margin_start(10)
    btn_localectl.set_margin_end(10)
    hbox_localectl.append(btn_localectl)

    # Systemd Services
    hbox_services = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_services = Gtk.Label(xalign=0)
    lbl_services.set_text("Systemd Services")
    btn_services = Gtk.Button(label="View")
    btn_services.connect("clicked", functools.partial(system.on_click_system_services, self))
    lbl_services.set_margin_start(10)
    lbl_services.set_margin_end(10)
    lbl_services.set_hexpand(True)
    hbox_services.append(lbl_services)
    btn_services.set_margin_start(10)
    btn_services.set_margin_end(10)
    hbox_services.append(btn_services)

    # System Services Enabled
    hbox_services_enabled = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_services_enabled = Gtk.Label(xalign=0)
    lbl_services_enabled.set_text("System Services Enabled")
    btn_services_enabled = Gtk.Button(label="View")
    btn_services_enabled.connect(
        "clicked", functools.partial(system.on_click_system_services_enabled, self)
    )
    lbl_services_enabled.set_margin_start(10)
    lbl_services_enabled.set_margin_end(10)
    lbl_services_enabled.set_hexpand(True)
    hbox_services_enabled.append(lbl_services_enabled)
    btn_services_enabled.set_margin_start(10)
    btn_services_enabled.set_margin_end(10)
    hbox_services_enabled.append(btn_services_enabled)

    # Systemd Services Failed
    hbox_services_failed = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_services_failed = Gtk.Label(xalign=0)
    lbl_services_failed.set_text("Systemd Services Failed")
    btn_services_failed = Gtk.Button(label="View")
    btn_services_failed.connect(
        "clicked", functools.partial(system.on_click_system_services_failed, self)
    )
    lbl_services_failed.set_margin_start(10)
    lbl_services_failed.set_margin_end(10)
    lbl_services_failed.set_hexpand(True)
    hbox_services_failed.append(lbl_services_failed)
    btn_services_failed.set_margin_start(10)
    btn_services_failed.set_margin_end(10)
    hbox_services_failed.append(btn_services_failed)

    # Systemd Timers Enabled
    hbox_timers_enabled = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_timers_enabled = Gtk.Label(xalign=0)
    lbl_timers_enabled.set_text("Systemd Timers Enabled")
    btn_timers_enabled = Gtk.Button(label="View")
    btn_timers_enabled.connect(
        "clicked", functools.partial(system.on_click_system_timers_enabled, self)
    )
    lbl_timers_enabled.set_margin_start(10)
    lbl_timers_enabled.set_margin_end(10)
    lbl_timers_enabled.set_hexpand(True)
    hbox_timers_enabled.append(lbl_timers_enabled)
    btn_timers_enabled.set_margin_start(10)
    btn_timers_enabled.set_margin_end(10)
    hbox_timers_enabled.append(btn_timers_enabled)

    # Kernel Ring Buffer
    hbox_dmesg = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_dmesg = Gtk.Label(xalign=0)
    lbl_dmesg.set_text("Kernel Ring Buffer (dmesg)")
    btn_dmesg = Gtk.Button(label="View")
    btn_dmesg.connect("clicked", functools.partial(system.on_click_system_dmesg, self))
    lbl_dmesg.set_margin_start(10)
    lbl_dmesg.set_margin_end(10)
    lbl_dmesg.set_hexpand(True)
    hbox_dmesg.append(lbl_dmesg)
    btn_dmesg.set_margin_start(10)
    btn_dmesg.set_margin_end(10)
    hbox_dmesg.append(btn_dmesg)

    # GParted
    hbox_gparted = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.lbl_gparted = Gtk.Label(xalign=0)
    self.lbl_gparted.set_markup(
        "Inspect with GParted" + (" <b>installed</b>" if fn.path.exists("/usr/bin/gparted") else "")
    )
    btn_gparted = Gtk.Button(label="Install")
    btn_gparted.connect("clicked", functools.partial(system.on_click_system_gparted, self))
    btn_gparted_remove = Gtk.Button(label="Remove")
    btn_gparted_remove.connect("clicked", functools.partial(system.on_click_system_gparted_remove, self))
    self.lbl_gparted.set_margin_start(10)
    self.lbl_gparted.set_margin_end(10)
    self.lbl_gparted.set_hexpand(True)
    hbox_gparted.append(self.lbl_gparted)
    btn_gparted.set_margin_start(10)
    btn_gparted.set_margin_end(10)
    hbox_gparted.append(btn_gparted)
    btn_gparted_remove.set_margin_start(10)
    btn_gparted_remove.set_margin_end(10)
    hbox_gparted.append(btn_gparted_remove)

    # Partition Manager
    hbox_partitionmanager = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.lbl_partitionmanager = Gtk.Label(xalign=0)
    self.lbl_partitionmanager.set_markup(
        "Inspect with Partition Manager"
        + (" <b>installed</b>" if fn.path.exists("/usr/bin/partitionmanager") else "")
    )
    btn_partitionmanager = Gtk.Button(label="Launch/install")
    btn_partitionmanager.connect(
        "clicked", functools.partial(system.on_click_system_partitionmanager, self)
    )
    btn_partitionmanager_remove = Gtk.Button(label="Remove")
    btn_partitionmanager_remove.connect(
        "clicked", functools.partial(system.on_click_system_partitionmanager_remove, self)
    )
    self.lbl_partitionmanager.set_margin_start(10)
    self.lbl_partitionmanager.set_margin_end(10)
    self.lbl_partitionmanager.set_hexpand(True)
    hbox_partitionmanager.append(self.lbl_partitionmanager)
    btn_partitionmanager.set_margin_start(10)
    btn_partitionmanager.set_margin_end(10)
    hbox_partitionmanager.append(btn_partitionmanager)
    btn_partitionmanager_remove.set_margin_start(10)
    btn_partitionmanager_remove.set_margin_end(10)
    hbox_partitionmanager.append(btn_partitionmanager_remove)

    # Section headers
    hbox_section_hardware = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section_hardware_lbl = Gtk.Label(xalign=0)
    hbox_section_hardware_lbl.set_markup("<b>Hardware</b>")
    hbox_section_hardware_lbl.set_margin_start(10)
    hbox_section_hardware_sep = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hbox_section_hardware_sep.set_hexpand(True)
    hbox_section_hardware_sep.set_valign(Gtk.Align.CENTER)
    hbox_section_hardware.append(hbox_section_hardware_lbl)
    hbox_section_hardware.append(hbox_section_hardware_sep)

    hbox_section_storage = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section_storage.set_margin_top(10)
    hbox_section_storage_lbl = Gtk.Label(xalign=0)
    hbox_section_storage_lbl.set_markup("<b>Storage</b>")
    hbox_section_storage_lbl.set_margin_start(10)
    hbox_section_storage_sep = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hbox_section_storage_sep.set_hexpand(True)
    hbox_section_storage_sep.set_valign(Gtk.Align.CENTER)
    hbox_section_storage.append(hbox_section_storage_lbl)
    hbox_section_storage.append(hbox_section_storage_sep)

    hbox_section_system = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section_system.set_margin_top(10)
    hbox_section_system_lbl = Gtk.Label(xalign=0)
    hbox_section_system_lbl.set_markup("<b>System</b>")
    hbox_section_system_lbl.set_margin_start(10)
    hbox_section_system_sep = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hbox_section_system_sep.set_hexpand(True)
    hbox_section_system_sep.set_valign(Gtk.Align.CENTER)
    hbox_section_system.append(hbox_section_system_lbl)
    hbox_section_system.append(hbox_section_system_sep)

    hbox_section_systemd = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section_systemd.set_margin_top(10)
    hbox_section_systemd_lbl = Gtk.Label(xalign=0)
    hbox_section_systemd_lbl.set_markup("<b>Systemd</b>")
    hbox_section_systemd_lbl.set_margin_start(10)
    hbox_section_systemd_sep = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hbox_section_systemd_sep.set_hexpand(True)
    hbox_section_systemd_sep.set_valign(Gtk.Align.CENTER)
    hbox_section_systemd.append(hbox_section_systemd_lbl)
    hbox_section_systemd.append(hbox_section_systemd_sep)

    # ======================================================================
    #                       VBOX STACK
    # ======================================================================

    vboxstack_system.append(hbox_title)
    vboxstack_system.append(hbox_sep)

    vboxstack_system.append(hbox_section_hardware)
    vboxstack_system.append(hbox_cpu)
    vboxstack_system.append(hbox_memory_disk)
    vboxstack_system.append(hbox_lspci)
    vboxstack_system.append(hbox_lsusb)
    vboxstack_system.append(hbox_lsmod)
    vboxstack_system.append(hbox_inxi)
    vboxstack_system.append(hbox_hwinfo)

    vboxstack_system.append(hbox_section_storage)
    vboxstack_system.append(hbox_lsblk)
    vboxstack_system.append(hbox_fdisk)
    vboxstack_system.append(hbox_fstab)
    vboxstack_system.append(hbox_gparted)
    vboxstack_system.append(hbox_partitionmanager)

    vboxstack_system.append(hbox_section_system)
    vboxstack_system.append(hbox_hostnamectl)
    vboxstack_system.append(hbox_localectl)
    vboxstack_system.append(hbox_dmesg)

    vboxstack_system.append(hbox_section_systemd)
    vboxstack_system.append(hbox_services)
    vboxstack_system.append(hbox_services_enabled)
    vboxstack_system.append(hbox_services_failed)
    vboxstack_system.append(hbox_timers_enabled)
